Connected!
Setting status to '!help | In 93 servers'
Setting status to 'Some accounts may of been deleted'
Setting status to 'Some accounts may of been deleted sorry'
Setting status to '!help | In 93 servers'
Setting status to '!help | In 93 servers'
Setting status to '!help | In 93 servers'
Setting status to '!help | In 93 servers'
Setting status to '!help | In 93 servers'
Setting status to '!help | In 93 servers'
Setting status to '!help | Have you tried !feedback?'
Setting status to '!help | In 95 servers'
Setting status to 'thanks for 90+ servers!'
  File "bot.py", line 27
    async def on_message(message):
        ^
SyntaxError: invalid syntax
  File "bot.py", line 27
    async def on_message(message):
        ^
SyntaxError: invalid syntax
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 207, in on_message
    user_r = reddit.redditor(user_info['reddit name'])  # makes user
KeyError: 'reddit name'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 188, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 188, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 188, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 84, in on_message
    subreddit = reddit.subreddit(subreddit_name)  # makes subreddit
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/helpers.py", line 180, in __call__
    return Subreddit(self._reddit, display_name=display_name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 436, in __init__
    "Either `display_name` or `_data` must be provided."
TypeError: Either `display_name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/550081736588001310.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/415873707689377802.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: USER_DOESNT_EXIST: 'that user doesn't exist' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Connected!
Setting status to '!help | In 95 servers'
Setting status to '!help | In 95 servers'
Setting status to '!help | In 96 servers'
Setting status to '!help | In 96 servers'
Setting status to '!help | In 98 servers'
Setting status to 'What do you want added to the bot? | !feedback'
Setting status to '!help | In 98 servers'
Setting status to 'What do you want added to the bot? | !feedback'
Setting status to '!help | In 97 servers'
Setting status to 'What do you want added to the bot? | !feedback'
Setting status to 'Have a good idea? Try !feedback'
Setting status to 'Have a good idea? Try !feedback [feedback here]'
Setting status to '!help | In 97 servers'
Setting status to 'Have a good idea? Try !feedback [feedback here]'
Setting status to '!help | In 99 servers'
Setting status to '!help | In 100 servers'
Setting status to 'Thanks for 100 servers'
Setting status to '!help | In 101 servers'
Setting status to '!help | In 107 servers'
Setting status to '!help | In 108 servers'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 84, in on_message
    subreddit = reddit.subreddit(subreddit_name)  # makes subreddit
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/helpers.py", line 180, in __call__
    return Subreddit(self._reddit, display_name=display_name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 436, in __init__
    "Either `display_name` or `_data` must be provided."
TypeError: Either `display_name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/517506101999304754.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 179, in on_message
    user_r = reddit.redditor(user_name)  # makes user
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 561, in redditor
    return models.Redditor(self, name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 113, in __init__
    raise TypeError("Either `name` or `_data` must be provided.")
TypeError: Either `name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 43, in on_message
    await message.channel.send(message.author.mention + ' thanks for the feedback! If you want to tell it to the devs face, do that here: discord.gg/ZmyYxQg.')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 75, in on_message
    await message.channel.send(random_post_url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 75, in on_message
    await message.channel.send(random_post_url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Connected!
Setting status to '!help | In 108 servers'
Setting status to '!help | In 113 servers'
Setting status to 'Have a good idea? Try !feedback [feedback here]'
Setting status to 'Post streams are coming soon!'
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/594899803595472912.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/137258043195916288.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/307672780747440128.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/307672780747440128.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/380462665358901268.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/470840904220016660.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 188, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 75, in on_message
    await message.channel.send(random_post_url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 141, in on_message
    await loadingMessage.edit(embed=sub)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/message.py", line 741, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 141, in on_message
    await loadingMessage.edit(embed=sub)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/message.py", line 741, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/377904903110262785.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 87, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: TOO_LONG: 'this is too long (max: 100)' on field 'subject'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: USER_DOESNT_EXIST: 'that user doesn't exist' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: USER_DOESNT_EXIST: 'that user doesn't exist' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/596079424680493096.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/583050600984346655.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/596079424680493096.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 207, in on_message
    user_r = reddit.redditor(user_info['reddit name'])  # makes user
KeyError: 'reddit name'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 81, in on_message
    loadingMessage = await message.channel.send(embed=loading)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 81, in on_message
    loadingMessage = await message.channel.send(embed=loading)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 81, in on_message
    loadingMessage = await message.channel.send(embed=loading)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/435200177217732633.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 205, in on_message
    with open("users/" + user_id + '.json') as user_data:
FileNotFoundError: [Errno 2] No such file or directory: 'users/157185374773313537.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 236, in on_message
    await loadingMessage.edit(message.author.mention + ' No connected account')
TypeError: edit() takes 1 positional argument but 2 were given
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 265, in on_message
    code) + '\n\nIf you are being spammed by codes, dm me here: https://discord.gg/ZmyYxQg')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 207, in on_message
    user_r = reddit.redditor(user_info['reddit name'])  # makes user
KeyError: 'reddit name'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 207, in on_message
    user_r = reddit.redditor(user_info['reddit name'])  # makes user
KeyError: 'reddit name'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 188, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Connected!
Setting status to '!help | In 116 servers'
Setting status to 'Sub streams are taking a little longer'
Setting status to '!help | In 136 servers'
Setting status to 'Sub streams are coming tomorrow give or take'
Setting status to 'Sub streams are coming tomorrow give or take!'
