Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 43, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 158, in on_message
    user_r = reddit.redditor(user_name)  # makes user
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 561, in redditor
    return models.Redditor(self, name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 113, in __init__
    raise TypeError("Either `name` or `_data` must be provided.")
TypeError: Either `name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 158, in on_message
    user_r = reddit.redditor(user_name)  # makes user
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 561, in redditor
    return models.Redditor(self, name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 113, in __init__
    raise TypeError("Either `name` or `_data` must be provided.")
TypeError: Either `name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 232, in on_message
    code) + '\n\nIf you are being spamed by codes, dm me here: https://bwac.pro/trb')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 232, in on_message
    code) + '\n\nIf you are being spamed by codes, dm me here: https://bwac.pro/trb')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 232, in on_message
    code) + '\n\nIf you are being spamed by codes, dm me here: https://bwac.pro/trb')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 232, in on_message
    code) + '\n\nIf you are being spamed by codes, dm me here: https://bwac.pro/trb')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: NO_USER: 'please enter a username' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 43, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Connected!
Setting status to '!help | In 79 servers'
